### ISSUE TITLE
Paper on GitHub process and RP meeting structure and changes

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#10]
Request for update of GitHub process and RP Meeting structure/changes

ACTION @Keith-Pembleton and @sarahcleary to commence work on paper

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - please send any comments to @Keith-Pembleton

**Comment by sarahcleary** [comment]
Also note that an action from the AI SC meeting was "RP to involve/notify/incorporate home organisation key personnel into the new GitHub process".

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - please forward any comments to @Keith-Pembleton prior to AI SC on Friday.

**Comment by sarahcleary** [comment]
Reopen issue - action from August AI SC Meeting - RP to provide report on GitHub processes at next SC meeting

**Comment by sarahcleary** [comment]
Reminder:  @APSIMInitiative/reference-panel to provide feedback to @Keith-Pembleton via email, phone etc..

**Comment by sno036** [comment]
@sarahcleary  - apologies for denseness. Feedback on what?

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - AI SC are interested in an update on how the 'new' RP processes/structure are working, in particular, the utilisation of GitHub.  Please feed any comments (positive and negative) to @Keith-Pembleton.  Sorry @sno036 for missing your message

**Comment by sarahcleary** [comment]
Ongoing Action.  
Propose Verbal update by @peter-devoil and/or @kchenu at next AI SC meeting.  Please feed any comments to either @peter-devoil, @kchenu or me.

**Comment by sarahcleary** [comment]
agree to be a verbal update. @APSIMInitiative/reference-panel to provide @peter-devoil with comments/input

**Comment by EnliWang** [comment]
I feel that current processes/structure are working well. The utilisation of GitHub helped tracking issues and communications in RP

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - please note any issues/suggestions
