### ISSUE TITLE
AI Reference Panel Meeting No. 2 - June 2022

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#100]
21 June 2022

Invitees: @sno036 @hol353 @EnliWang @yashvirchauhan @LouisAK @HamishBrownPFR @kchenu @Keith-Pembleton @peter-devoil @MarkLieffering @jbrider @sarchontoulis @JulianneLilley @rcichota @femiguez @hut104 @uqdrodri @uqschap7 @erik-van-oosterom @docalexwu 

Apologies - @kchenu

**Comment by JackieOuzman** [comment]
@APSIMInitiative/reference-panel 
Please provide any items for up coming meeting. Thanks

**Comment by sarahcleary** [comment]
Apologies - @docalexwu and @kchenu 
@kchenu - can you provide an update on the APSIM Virtual Issue prior to this meeting.

**Comment by JackieOuzman** [comment]
Proposed Agenda items - feel free to add/amend

1. Welcome & Apologies
2. Minutes & Outstanding Actions
2.1 Root Modelling. Sotirios / Dean
2.2 Soils Workshop/project, Workshop on soil “P” #18. Keith
2.3 Sensibility tests. Update on Improved systems for sensibility tests for all crop models. Dean
3. New developments. Input from the panel
4. Funding Projects for possible funding. Chair / Dean
4. Uptake on Next Gen. 
5. Teaching and Training. Teaching at UNL. Andrea
5.2 ISU Teaching. Update on ISU Workshop. Sotirios
5.3 Online Seminar. Review of current list videos.  Jackie
•	Livestock Modelling - Val Snow
•	Setting up Weather Files - Neville Hermann
•	Model Parameter sensitivity - Neil Huth
•	Crop production - Hamish Brown
How to write manager scripts - Peter DeVoil
5.4 APSIM Week Jackie / Dean
6. Australian Agronomy Conference Sep 2022 in Toowoomba. Jackie / Dean
7. APSIM virtual issue. Update on the special issue, number of EOIs, papers accepted. Karine / other
8. GitHub use. Dean
7. Engineer position. Dean

**Comment by JackieOuzman** [comment]
Please find attached the minutes from the  June 2022 meeting.
[Agenda items RP No2 mins.docx](https://github.com/APSIMInitiative/ReferencePanel/files/8973183/Agenda.items.RP.No2.mins.docx)
