### ISSUE TITLE
Improving Next Gen Documentation to include summary page

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#12]
@HamishBrownPFR and GH working on "next gen documentation"

ACTION Hamish to organise to meet Graeme in person when visiting in August to work through documentation.

**Comment by sarahcleary** [comment]
@HamishBrownPFR -reminder for meeting with Graeme.

**Comment by sarahcleary** [comment]
@HamishBrownPFR - please update once you've spoken to Graeme

**Comment by HamishBrownPFR** [comment]
I met with Greame on the 23rd of Aug and have clarified what is needed.  I will prepare this and circulate.

**Comment by sarahcleary** [comment]
@HamishBrownPFR - any update?

**Comment by sarahcleary** [comment]
@HamishBrownPFR - sorry, removed this from the agenda.  Only to be discussed if you feel necessary or have had a chance to circulate doc.

**Comment by HamishBrownPFR** [comment]
Thats OK, no progress so no need to discuss

**Comment by sarahcleary** [comment]
@HamishBrownPFR - any update?

**Comment by sarahcleary** [comment]
@HamishBrownPFR - any update?

**Comment by sarahcleary** [comment]
@HamishBrownPFR - any update?

**Comment by sarahcleary** [comment]
@HamishBrownPFR - any update?

**Comment by sarahcleary** [comment]
uploaded onto website - https://www.apsim.info/apsim-model/description-of-crop-growth-and-development-framework-in-apsim-crop-models/
