### ISSUE TITLE
Organise workshop on harmonising approaches for development of crop models/crop processes

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#19]
Action from Feb 2019 RP Strategy Session
UQ to Lead.  Who else wants/should be involved?

**Comment by sarahcleary** [comment]
Any update @peter-devoil and/or @kchenu?

**Comment by sarahcleary** [comment]
@peter-devoil followed up internally with UQ.  Awaiting update

**Comment by sarahcleary** [comment]
@peter-devoil - any update?

**Comment by sarahcleary** [comment]
@peter-devoil - any update?

**Comment by sarahcleary** [comment]
@peter-devoil - any update?

**Comment by sarahcleary** [comment]
@peter-devoil - any update?

**Comment by peter-devoil** [comment]
The RP discussion was related to the process of moving  from APSIM Classic to APSIM Next Gen, and how to do better next time.  The issue can be closed.
