### ISSUE TITLE
Discussion on leveraging resources between members

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#21]
Action from Feb 2019 RP Strategy Session 
Noted that it is difficult to fund implementation.  Science development is easier to source funding, but without the implementation step, the science can not be utilised in APSIM.  Impact is low. 
Enli and Hamish to discuss leveraging resources including PhD students.

**Comment by sarahcleary** [comment]
Any update @HamishBrownPFR / @EnliWang ?

**Comment by sarahcleary** [comment]
Any update @HamishBrownPFR / @EnliWang ?

**Comment by HamishBrownPFR** [comment]
Discussed with Neil, Enli, Hamish.  Need more people with the implementation skills to get things back into version control and into release.  Often it is beyond the scope of projects to get science back into release.
Need to get specific people in key development groups to take responsibility for supporting other scientists in the group to get stuff back into release.

**Comment by sarahcleary** [comment]
Feedback discussion to AI SC committee.  @sarahcleary to add it to an agenda item for the SC meeting.

**Comment by sarahcleary** [comment]
Minutes from last AI SC meeting:  HB was not present so KP provided a short summary:
•	In most projects, not enough funding allocated to ensure that model development is included into release.  Major issue is that there are not enough people with the skill and/or capacity for translating the science developments into an APSIM model
•	Opportunity to provide the SC with a proposal to propose a solution (if there is one), assuming this is a practical rather than a cultural problem.  This may be through resourcing or another mechanism.
ACTION:  RP to review issue; identify specific cases and potential put a proposal together for the SC to review.
@HamishBrownPFR - will you be at Tuesday's meeting to lead this discussion?

**Comment by sarahcleary** [comment]
@HamishBrownPFR - will you be at Tuesday's meeting to lead this discussion?

**Comment by sarahcleary** [comment]
Closing this issue as will be discussed in the RP Strategy session in June
