### ISSUE TITLE
Workshop on Carbon decomposition and nitrogen mineralisation

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#22]
Action from Feb RP Strategy Session
Organise workshop on Carbon decomposition and nitrogen mineralisation  – potentially implementation tasks can be broken up for student development
Who should be involved?

**Comment by sarahcleary** [comment]
@EnliWang - this was assigned to you.  Any update/thoughts on who should be involved?

**Comment by sarahcleary** [comment]
@EnliWang - any update/comments?

**Comment by sarahcleary** [comment]
@EnliWang to discuss with @hut104

**Comment by sarahcleary** [comment]
@EnliWang - please close if complete

**Comment by sarahcleary** [comment]
@EnliWang - please close if complete

**Comment by sarahcleary** [comment]
@EnliWang - please close if complete

**Comment by sarahcleary** [comment]
@EnliWang - please close if complete

**Comment by sarahcleary** [comment]
@EnliWang - can this issue be closed?

**Comment by EnliWang** [comment]
This would be best done with the progress of the nutrient model in APSIM Next Gen. 
I will also highlight the issues in my presentation at APSIM symposium and see whether we receive attentions.
We close it for now and can re-open it if there are enough interests. I will also discuss with Neil for future plans to do this.
