### ISSUE TITLE
Discussion on Root System developement

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#24]
Action from Feb RP Strategy Session
Organise discussion on Root System development – Hamish to lead – include Karine; Enli
Anyone else wants to be involved?

**Comment by sarahcleary** [comment]
Any update - @HamishBrownPFR / @EnliWang / @kchenu / @sno036 ?

**Comment by sarahcleary** [comment]
Any update - @HamishBrownPFR / @EnliWang / @kchenu / @sno036 ?

**Comment by HamishBrownPFR** [comment]
Discussed with Neil, Enli, Hamish. 
Would be good for someone to put a concerted effort into collecting root data sets, running apsim against them and comming up with some improvements to the room modelling approach which is currently very simple and not broadly tested.
Try to find a student to work on this.

**Comment by kchenu** [comment]
I'd be happy to help on this now that I'm back in the office. I also have a PhD student working on root system in wheat (more towards doing some genetics) but there may be some measurements/traits we could help with.

**Comment by sarahcleary** [comment]
@EnliWang, @kchenu and @sarchontoulis to discuss.

**Comment by sarahcleary** [comment]
@EnliWang, @kchenu and @sarchontoulis - can this issue be closed?

**Comment by sarahcleary** [comment]
@EnliWang, @kchenu and @sarchontoulis - can this issue be closed?

**Comment by sarahcleary** [comment]
@EnliWang, @kchenu and @sarchontoulis - can this issue be closed?

**Comment by sarahcleary** [comment]
@EnliWang, @kchenu and @sarchontoulis - can this issue be closed?

**Comment by sarahcleary** [comment]
@EnliWang, @kchenu and @sarchontoulis - can this issue be closed?

**Comment by EnliWang** [comment]
One of my PhD students (Yang Lu) worked on this with her data from North China and APSIM NG. She is putting results together - this is for both root length, root biomass, and root N distribution of wheat. Detailed data, but with limited treatments (environments).

**Comment by sarchontoulis** [comment]
We have collected similar root data from Iowa on maize and soybean crops. About 30 site-years including N treatments for maize. The plan is to start working on modeling these data with APSIM NG in 2020.

**Comment by sarahcleary** [comment]
@sarchontoulis and/or @EnliWang - any update?

**Comment by sarahcleary** [comment]
@sarchontoulis and/or @EnliWang - close this issue?  covered by other conversations?

**Comment by sarchontoulis** [comment]
Yes, covered by other conversations
