### ISSUE TITLE
Discussion on Maize and Soybean – microclimate development

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#25]
Action from Feb RP Strategy Session
Organise discussion on Maize and Soybean – microclimate development – Neil; Val; Enli; Hamish

**Comment by sno036** [comment]
Add to the list:
- managing the energy balance (who does soil water evaporation for example)
- layering clunky (and was a recent issue with a canopy depth issue)
- issues with high latitudes
- not enough outputs

Add more dot points in the discussion to cover other issues.

Should we try for an online meeting in late July for a proper discussion once we have a more complete list of issues?

**Comment by HamishBrownPFR** [comment]
This probably ties in with with work in fruit tree modelling.  I have a pull request open at the moment that allows for non-zero base heights (i.e canopy depths that are less than height) and taller canopys to overlap the zone space of the shorter canopies.
I think we should consider having microclimate do all evaporation (from leaves, residues and soil) so we can ensure evaporation demands are partitioned effectively.  
We have recently made a change that allows plants to have multiple organs interfacing with microclimate by having multiple organs implement ICanopy and having Microclimate interface through these.  This is currently used so leaves and stems can both intercept radiation, photosynthesize and transpire.  This could be extended by having residuals implement Icanopy also so microclimate would deal with their interception and evaporation also.  This could be extended to separating leaf into multiple layers

**Comment by sno036** [comment]
Yeah - it is supposed to be able to deal with non-zero bases and differential overlapping! I was sure (although it was a long time ago and was in the original Fortran version) that combinations like that were tested. Add to the discussion points.

@hut104 tagged into the conversation.

**Comment by sarahcleary** [comment]
Any progress towards an online meeting to progress this?

**Comment by sarahcleary** [comment]
Any update?

**Comment by HamishBrownPFR** [comment]
Discussed with Neil, Hamish Enli.  
There code for modelling strip crops is implemented into microclimate.  Should be possible to run Maize SoyBean intercrops.  
Soybean not in release yet but good prototype ready
Suggest making this an issue specificly about microclimate improvements

**Comment by sarahcleary** [comment]
Close issue as @HamishBrownPFR to commence major issue for review of microclimate improvements

**Comment by sarahcleary** [comment]
@HamishBrownPFR - please close when major issue opened

**Comment by HamishBrownPFR** [comment]
Transferred to https://github.com/APSIMInitiative/ApsimX/issues/4217
