### ISSUE TITLE
RP Meetings - Invite speakers

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#26]
Action from Feb RP Strategy Meeting
RP wishes to keep abreast of best practice.  One way of doing this is by actively seeking input from others about different modelling approaches.
Invite people to present on relevant topics at RP meetings.

(1) invite the CLEM development group to present.

**Comment by sarahcleary** [comment]
Invited @pre078 and/or @lie112 to present at August RP meeting.
@yashvirchauhan to present at July RP meeting - in person in TWB.

**Comment by sarahcleary** [comment]
Invite @hut104 and @sarchontoulis to present work on the new soybean model work to RP - https://github.com/APSIMInitiative/ApsimX/issues/2731

**Comment by sarahcleary** [comment]
@sarchontoulis to provide update and learnings from ISU workshop in August RP meeting

**Comment by peter-devoil** [comment]
@peter-devoil to do a walk through of the ApsimX graphical crop rotation manager before the end of the year - october?

**Comment by sarahcleary** [comment]
@sarchontoulis - are you still able to provide an update in the next RP meeting?

**Comment by sarahcleary** [comment]
@sarchontoulis - we have you down to provide an update on the ISU workshop/training in the next RP meeting.  Please let me know if you are unable to attend.

**Comment by sarahcleary** [comment]
@peter-devoil unlikely to attend the Oct RP Meeting.   Maybe present APSIMX crop rotations manager in the Nov RP meeting.
@APSIMInitiative/reference-panel - any suggestions for Oct or future meetings?

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - please provide any thoughts for future meetings.

**Comment by sarahcleary** [comment]
Suggestions for future meetings:
•	Nutrient Model – @hut104 and @sno036   

•	Sensitivity analysis in Next Gen – @hut104 

•	Pest work – Jeremy Whish and @sno036 

@sarahcleary to contact the above people.  Noted that they are unlikely to be available for the December 2019 meeting.

**Comment by sarahcleary** [comment]
Delayed until April meeting.  
Proposed topics
• Nutrient Model – @hut104 and @sno036
• Sensitivity analysis in Next Gen – @hut104
• Pest work – Jeremy Whish and @sno036
@APSIMInitiative/reference-panel - any other topics/people?

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - any other topics/people?
@hut104 and @sno036 - are you available on the 7/4 for the RP meeting (approx. 10:30am AEST)?

**Comment by hut104** [comment]
Should be ok

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sarahcleary** [comment]
@jwhish - FYI

**Comment by sno036** [comment]
Yes.

**Comment by sarahcleary** [comment]
Presentation on Nutrient Model – @hut104 and @sno036 
@hut104 - will send dial in details for next Tuesday.

**Comment by sarahcleary** [comment]
@jwhish - would you be available to attend the next RP meeting - 5/5 at approx. 10:30am to provide an update on the Pest framework?

**Comment by sarahcleary** [comment]
@jwhish - meeting request sent. Please phone in at approx. 10:30 on 5/5.  thanks

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - any thoughts/requests for updates/speakers?

**Comment by Keith-Pembleton** [comment]
From an interest point of view what about Mark Silburn from DNRM to talk about the P2R modeling program (APSIM is one of many models used).

**Comment by sarahcleary** [comment]
thanks @Keith-Pembleton.  Email to Mark sent

**Comment by sarahcleary** [comment]
Mark is joining us for the next RP meeting.  @APSIMInitiative/reference-panel - please think about other possible presenters

**Comment by sarahcleary** [comment]
Closing as this will be captured in the new agenda format for the longer, less frequent, meetings.
Calls for invited speakers will be made as we develop the agendas.
