### ISSUE TITLE
Update of APSIM download screen to enable email addresses to be used for APSIM communication purposes

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#32]
As per RP discussion, @APSIMInitiative/reference-panel agreed to include this as part of the download process. 

@hol430 - can you please look at updating the downloading process.  Requirements:

- request for email address (which I think already happens)

- statement that "The APSIM Initiative will forward updates on APSIM-related developments and improvements as well as upcoming APSIM-related events including training workshops."

Is it possible to do an opt-out there - or we will need to provide an unsubscribe button as part of any email we send with regard to these updates/notifications.

**Comment by hol430** [comment]
What exactly would people be opting out of?

**Comment by sarahcleary** [comment]
Opting out of receiving emails from apsim@csiro.au with regard to notifications.  Maybe a better term is 'unsubscribe' option

**Comment by hol430** [comment]
Which emails are you referring to? I've never received an email from that address related to events/workshops.

**Comment by sarahcleary** [comment]
The intention is for emails to be sent from this email.  However, before we can do this, we need to ensure that (1) we communicate with people that their email may be used for this purpose and (2) they have the option of unsubscribing from receiving such emails.

**Comment by JulianneLilley** [comment]
Agree that unsubscribe is probably better terminology

**Comment by sarahcleary** [comment]
@hol430 - any update?  or further question/need to clarity?

**Comment by hol430** [comment]
It's done. If you go to the registration page, you'll see there's an option to subscribe to the mailing list. There's still no way to send an email to the mailing list, for now we are only collecting emails.
