### ISSUE TITLE
Potential Facilitators for APSIM Advanced Training workshops

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#33]
@APSIMInitiative/reference-panel (or others) to suggest potential facilitators (or nominate themselves) for the following Advanced training workshops:
Crop production, crop growth and development 
Crop rotations
Livestock Modelling
APSIM in Cloud Platforms
Model Parameter sensitivity
Transition from APSIM Classic to Next Gen
Whole of Farm Modelling
How to write manager scrips
Agroforestry

**Comment by sarahcleary** [comment]
@pre078 willing to run CLEM workshop
@sme016 - Agroforestry

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - any further suggestions?  self-nominations?

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - any further suggestions? self-nominations?

**Comment by hol353** [comment]
Model Parameter sensitivity: Neil Huth
APSIM in Cloud Platforms: Loretta Clancy and Drew Holzworth
Transition from APSIM Classic to Next Gen: Dean Holzworth
Livestock Modelling: Val Snow and/or Neville Herrmann
Agroforestry: Phil Smethurst and Neil Huth

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - Request for suggested facilitators

**Comment by HamishBrownPFR** [comment]
@HamishBrownPFR  could contribute to Crop production, crop growth and development if it is APSIM next gen based

**Comment by sno036** [comment]
Livestock Modelling: Val Snow **and** Neville Herrmann at least (someone should probably let Neville know!). Need to make it known will be NextGen.

**Comment by MarkLieffering** [comment]
I am happy to be a floater rather than a facilitator - assuming I get sufficiently up to speed with Next Gen!

**Comment by sarahcleary** [comment]
@HamishBrownPFR - Can you please provide a few sentences for a description of this (Crop production, crop growth and development (APSIM Next Gen)) workshop? 
https://apsim-wp.csiro.au/support/apsim-symposium-and-advanced-training-workshops/apsim-advanced-workshops/  @jbrider

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - if you haven't already, please let me know which workshops you are happy to help 'support'

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - additional 'support' to be finalised. 
Please review https://www.apsim.info/support/apsim-symposium-and-advanced-training-workshops/apsim-advanced-workshops/ - bottom of page and let me know where you can help.  It would be good to have 4-5 people per workshop (noting that this number may not be needed, depending on participants).

**Comment by sme016** [comment]
Hi Sarah,

Agroforestry workshop: What are the numbers now? When will a decision be made to (1) run it, (2) or not, or (3) cut it back in cost and delivery time? Even if cancelled (1), I’d like to offer something to the few who had registered, e.g. brief overview, how to get started, informal Q&A and Webex follow-up help to get underway, even if I do this later than that week.

I’ll be happy to help as works best for you, but my preferences are:
Thurs am             Crop rotations
Fri am                   Not available as I have already registered for Livestock Modelling
Fri pm                   APSIM in Cloud

If the agroforestry workshop goes ahead, that obviously takes me out of potential help in others Thurs pm. If it is cancelled my preference is for:
Thurs pm             Whole of Farm Modelling


Note that I think Classic should be changed to 7.10 in the screen below (and anywhere else it occurs) to reduce confusion.
[cid:image003.jpg@01D5DA96.10A4C100]

Thanks,
Philip

**Comment by sarahcleary** [comment]
thanks @sme016.  The numbers are still low so was going to discuss this at the RP meeting tomorrow.  Thank you for your offer for help - have put you down for APSIM in Cloud and Crop Rotations to help.  Will be able to answer your question tomorrow.

**Comment by sme016** [comment]
Thanks,
Philip

**Comment by sarahcleary** [comment]
Still looking for support on some of the workshops.  @APSIMInitiative/reference-panel - please review - https://www.apsim.info/support/apsim-symposium-and-advanced-training-workshops/apsim-advanced-workshops/  (bottom of webpage)

**Comment by peter-devoil** [comment]
I'm wondering if there are any more volunteers for the Manager workshop - I suspect it's going to need a lot of hands on assistance. So far we have 3 (for 15 attendees).

**Comment by zur003** [comment]
@peter-devoil - I think I should be available to assist.

**Comment by peter-devoil** [comment]
Thanks, eric. You're aware it's on at the same time as livestock modelling

**Comment by sarahcleary** [comment]
@zur003 - I have you down as attending the CLEM workshop.  I'll put you on the list as support for the "How to write manager scripts (APSIM 7.10)" workshop.  Thank you!  Or were you intending on supporting the Livestock modelling one (we currently have @sno036; @her123 facilitating that one, with @jbrider, @MarkLieffering and @lie112 supporting).

**Comment by zur003** [comment]
Where is the greater need?

**Comment by sarahcleary** [comment]
In my opinion, @peter-devoil's workshop.  However, I cc'ed the livestock modelling group as an FYI.

**Comment by jbrider** [comment]
@sarahcleary @zur003 I'm more of a spectator in the stock workshop if you don't have to enough to cover both.

**Comment by sno036** [comment]
@sarahcleary - I am involved in workshops all Friday. I would like to go to CLEM on Thursday afternoon. I can help out wherever needed on Thursday morning.

**Comment by sarahcleary** [comment]
@sno036 - I know @hol353 wanted a few extra hands for the Transition workshop.  Will put you down for that one.

**Comment by sarahcleary** [comment]
@sno036 - also put you down as support for CLEM.

**Comment by sno036** [comment]
> also put you down as support for CLEM.
😊 I thought I might be a student!
