### ISSUE TITLE
19/20 APSIM Development Plan

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#36]
Email with new format sent to @APSIMInitiative/reference-panel.  No longer capturing anticipated commitment but just Start/End Dates and Project Leader. 
Additional Action from August 2019 AI SC Meeting - RP to consider if it’s possible, to include 3rd party developments and in what format on the development plan.

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel -please update development plan shared via OneDrive

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - can you please review and update this document prior to the next RP meeting - https://csiroau-my.sharepoint.com/:x:/r/personal/cle11c_csiro_au/Documents/APSIM_RP%20Shared%20Folder/20190912%20Development%20Plan.xlsx?d=w49354e49d7ca4080b0430629bdc31ba6&csf=1&e=065O85 
If you wish to share this with your colleagues, can you please send me their email address and I will provide them access.

**Comment by LouisAK** [comment]
> @APSIMInitiative/reference-panel - can you please review and update this document prior to the next RP meeting - https://csiroau-my.sharepoint.com/:x:/r/personal/cle11c_csiro_au/Documents/APSIM_RP%20Shared%20Folder/20190912%20Development%20Plan.xlsx?d=w49354e49d7ca4080b0430629bdc31ba6&csf=1&e=065O85
> If you wish to share this with your colleagues, can you please send me their email address and I will provide them access.

Hi Sarah,
I tried to access the document and I got an error message indicating that my email address can't be found in the csiroau-my.sharepoint.com directory. Any idea to overcome this? Thanks

**Comment by sarahcleary** [comment]
Requires updating prior to the March AI SC meeting.  Can all @APSIMInitiative/reference-panel reps review this document:  https://csiroau-my.sharepoint.com/:x:/r/personal/cle11c_csiro_au/Documents/APSIM_RP%20Shared%20Folder/20200106_Development%20Plan%20(for%20March%202020%20AI%20SC%20meeting).xlsx?d=w90761b4a77554500b4f850a89b83c02c&csf=1&e=MgWaAk

**Comment by sarahcleary** [comment]
Please note link is in RP Strategy agenda which has been circulated.  If you are unable to access it, please let me know

**Comment by sarahcleary** [comment]
Email request sent 11/2.  @APSIMInitiative/reference-panel - please review and update where required.

**Comment by sarahcleary** [comment]
ACTION from last RP meeting: @APSIMInitiative/reference-panel to send request/development to team to update development plan and/or at least engage in internal conversation around current and future work.
