### ISSUE TITLE
Improved GitHub Communication

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#37]
Action from AI SC Meeting:  Increased communication around GitHub process/use.  
@sarahcleary to provide a ‘how to sign up’; basic instructions on use for APSIM related work and with APSIM developers.  Input welcome from @APSIMInitiative/reference-panel

**Comment by sarahcleary** [comment]
@HamishBrownPFR - I note this action from the last RP meeting - @HamishBrownPFR - to look into any filtering mechanisms able to be used on GitHub - ‘teams’, label, tagging etc.. Possibly set up teams for different areas. Any software to help manage GitHub?

**Comment by HamishBrownPFR** [comment]
Hi Sarah.  
I have been trailing a piece of software called "DevHub" which is purpose built for managing github notifications.  I find it much better than dealing with them through email.  I can give an update on this at the next RP meeting

**Comment by Keith-Pembleton** [comment]
Thanks Hamish
That would be great if you could give us an overview of DevHub in the RP meeting.  If you think it would be worthwhile having the RP members have a look at it prior please send around a relevant link
Cheers
Keith

**Comment by sarahcleary** [comment]
@HamishBrownPFR - would you mind providing the link for DevHub?

**Comment by HamishBrownPFR** [comment]
https://github.com/devhubapp/devhub

**Comment by sarahcleary** [comment]
Close issue as now https://github.com/APSIMInitiative/ReferencePanel/issues/41
