### ISSUE TITLE
Soil temp

### ISSUE THREAD

**Issue by yashvirchauhan** [APSIMInitiative/ReferencePanel#39]
I have been using Soiltemp in APSIM classic for quite a while. Tthe major difference in soil temperature simulated by Soiltemp and that simulated by soilN module is when soil is covered by the crop canopy. Soil N based simulated temperature is much higher (>2-5oC) indicating it is not able correctly simulate soil temp when radiation reaching soil is reduced - if I correctly remember. Soil temperature is used in predicting aflatoxin risk in peanuts and the values predicted by soil temp were more realistic.

**Comment by sarahcleary** [comment]
Closing issue as comment now include in: https://github.com/APSIMInitiative/ApsimX/issues/4080
