### ISSUE TITLE
APSIM online training topics

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#42]
@APSIMInitiative/reference-panel - suggestions requested for online/video training topics.

**Comment by hol353** [comment]
There are many topics that are worthy of training videos from beginner tutorials (@Keith-Pembleton  is doing a great job creating these) to more advanced topics like:

- How to run a parameter sensitivity analysis
- How to create a grazing simulation.
- How does the experiment node work in APSIM Next Generation?
- How do I run simulations on a compute cloud?
- How to write manager scripts.
...

These can be created over time when / if someone has the time to create the videos. 

Lots of people would prefer text based step-by-step tutorials while others would like videos. Given limited resources, what is the preference?

**Comment by sno036** [comment]
For these advanced topics I'm struggling to see how a video as a standalone would work. I think that well-documented tutorial-style example simulation is likely to be better (and they can be kept current by being part of the build testing). I could see a role for a video as an adjunct to a tutorial simulation - e.g. explaining how Intellisense works, debugging a 'object reference bug', ...

**Comment by Keith-Pembleton** [comment]
My experience from using APSIM for the tutorials in my Agronomy course is it is about 50:50 with regard preference for text based vs videos.  As the videos are based of our existing text materials for APSIM classic so we have both.  When it comes to APSIM nextgen we will need to create some text materials plus the tutorial simulations before creating the videos.

**Comment by sarahcleary** [comment]
Refer to Minutes:
@sno036 suggested tutorial style for sensitivity analysis.
Need to transition the basic training from APSIM 7.10 to APSIM Next Gen.
ACTION: @sarchontoulis, @Keith-Pembleton and @hol353 to discuss the migration of the training materials

Any update - @sarchontoulis, @Keith-Pembleton and/or @hol35

**Comment by sarahcleary** [comment]
Just a reminder for @sarchontoulis, @Keith-Pembleton and @hol353 to discuss the migration of the training materials.
@APSIMInitiative/reference-panel - still looking for additional training topics/training material and/or people willing to record a video or two.

**Comment by sarahcleary** [comment]
Just a reminder for @sarchontoulis, @Keith-Pembleton and @hol353 to discuss the migration of the training materials.
@APSIMInitiative/reference-panel - still looking for additional training topics/training material and/or people willing to record a video or two.
Note new videos from Keith - https://www.youtube.com/channel/UCawR0E_PzYJcv15oTk-ssjQ/videos

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel requested to think about additional topics and if they could/would record additional training videos.  Any of the advanced training material being developed able to be converted to online videos?

**Comment by sarahcleary** [comment]
Please note new videos have been uploaded - https://www.apsim.info/support/videos/

**Comment by sarahcleary** [comment]
I've been getting a reasonable number of requests recently around training documentation for Next Gen.  Do you think a coordinated approach, leveraging off what people have been doing (or planning to do) would be advisable and help (1) progress and (2) produce good/useful quality material?   @cla473; @sarchontoulis; @hol353; @peter-devoil; @Keith-Pembleton; @hut104 - and others!   Any suggestions of a way to progress?  would you be happy with an initial teleconference - maybe early one morning to accommodate @sarchontoulis

**Comment by sarahcleary** [comment]
https://github.com/APSIMInitiative/ApsimX/issues/5807#issuecomment-718244126
