### ISSUE TITLE
Concept Notes

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#57]
@APSIMInitiative/reference-panel  - as per email - Identify major issues which require a ‘concept note’.  Background - Ideally, a concept note is an introduction to the GitHub issue - it should include a brief description of the science domain, how the new work is derived from and differs from previous or other models, an estimation of what new functionality will be developed and/or anything else that the non-programming audience will find of interest. The main reason behind this request to grow the GitHub audience and this will make it easier for new users to engage with GitHub and therefore APSIM in the long term.  
Comments, suggestions welcome

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - please note outstanding action.   As RP reps, can you please update any issue you have with 'concept note' - these should be at least the major issues (new models)

**Comment by sarahcleary** [comment]
Concept notes still required for these models:

New Chickpea model -  https://github.com/APSIMInitiative/ApsimX/issues/158 - @hut104 

New Cotton Model - https://github.com/APSIMInitiative/ApsimX/issues/4631 - @hut104 

Grape Vine Model -  https://github.com/APSIMInitiative/ApsimX/issues/1822 - @HamishBrownPFR 

Create a new peanut model - https://github.com/APSIMInitiative/ApsimX/issues/4075 - @hol353 

New Lentil Model - https://github.com/APSIMInitiative/ApsimX/issues/5288  @peter-devoil

**Comment by hol353** [comment]
Peanut model is @hut104 not me.

**Comment by sarahcleary** [comment]
@peter-devoil - were you going to follow these up?

**Comment by peter-devoil** [comment]
Yes. The lentil one is done.

**Comment by sarahcleary** [comment]
Still awaiting Concept Notes on the following issues:

New Cotton Model - APSIMInitiative/ApsimX#4631 - @hut104

Grape Vine Model - APSIMInitiative/ApsimX#1822 - @HamishBrownPFR

**Comment by hut104** [comment]
I’ve added a little more detail.  Not sure what we can really say though.

**Comment by sarahcleary** [comment]
Closing as currently complete.  Can open again if required.
