### ISSUE TITLE
Invite colleagues and others to GitHub Org

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#58]
@APSIMInitiative/reference-panel - As per email - request colleagues from your member org to join the APSIM Initiative GitHub Organisation.   To do this, they will need to create an account on GitHub. They would then be able to join any of the ‘teams’ that are relevant to their work, observing and/or becoming part of the conversations about new developments in APSIM.  The reason behind this request is that the AI is utilising GitHub not only as its development platform but also as its main communication and engagement platform.   We are trying to encourage the APSIM community to engage on both science and software issues via GitHub, and without participation, we won't have engagement. We'll try to find some videos (relevant to non-programmers/coders) that make the experience less overwhelming.

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - please note action to invite your colleagues to GitHub

**Comment by peter-devoil** [comment]
Here's some videos that aren't totally code-focussed. They provide some insights into issue tracking and the uses of markdown

-  What do non-technical people use git for https://www.youtube.com/watch?v=pY5i0Io86UQ (gitlab isnt exactly the same as github but principles are the same)

-  Github & project management - https://www.youtube.com/watch?v=OIE_KXnSOXY

-  Github for poets - issues: https://www.youtube.com/watch?v=WMykv2ZMyEQ

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - we currently have 50 people as members of the AI GitHub organisation.  I'm sure there are others.  Can you please check in with your group/colleagues and see if they have signed up/been invited?  Also, if there is confusion, lack of clarity etc.. please let me know and we can work up some further instructions.  You will note @peter-devoil's comment above which provides some links to 'how to' GitHub videos.
