### ISSUE TITLE
Projects for potential funding

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#62]
ACTIONS from the June 2020 RP Strategy Session:
**Projects for potential funding**
https://github.com/APSIMInitiative/ApsimX/issues/5360 - Potentially organise a workshop.  Maybe a candidate for seed funding depending on scope of workshop/work proposed. 
https://github.com/APSIMInitiative/ApsimX/issues/158 -  requires a short development sprint. Would assist completion by end of year.  Candidate for seed funding for development sprint. 
https://github.com/APSIMInitiative/ApsimX/issues/1254 - it’s an essential component of many systems yet is ¾ built with no immediate prospect of completion.   Candidate for seed funding
https://github.com/APSIMInitiative/ApsimX/issues/4080 - May do a sprint later this year and apply for travel assistance from SC. Val & Keith to develop plan that may include MSc.  Candidate for seed funding

@APSIMInitiative/reference-panel - anything else? Can you please nominate to write a short proposal if it's in your domain?

**Comment by sarahcleary** [comment]
@HamishBrownPFR  - were there any other issues/projects from previous meetings you wish to add to this list?

**Comment by HamishBrownPFR** [comment]
A sprint to tidy up Next Gen Auto doc.

**Comment by sno036** [comment]
From my point of view:
- APSIMInitiative/APSIMClassic#1870 (P model) is too big for AI funding. I find it hard to imagine a small piece of work that would add value (and it is in Classic - AI-funded work should be in NG)
- APSIMInitiative/ApsimX#158   (Chickpea) yes if this would get it over the line - what is the llimitation to getting it finished?
- APSIMInitiative/ApsimX#1254 (SWIM) agree high priority - need to buy someone's time
- APSIMInitiative/ApsimX#4080 (SoilTemp) this is needed for all/most simulations. Limitation is time. A development spring (could be virtual) would assist but only if get enough time from the right people
- @HamishBrownPFR suggested AutoDoc - good idea

**Comment by peter-devoil** [comment]
Sorry @sno036 , the P item is a mistake - it should refer to paddy N capability. I'll fix it shortly.

@APSIMInitiative/reference-panel - If funding is being requested, the SC is going to need a little background, and I'm calling for volunteers to write a (1/2 page ?) justiification on each. Sarah needs to present these by mid-july.

**Comment by peter-devoil** [comment]
The paddy module issue is https://github.com/APSIMInitiative/ApsimX/issues/5360

**Comment by sarahcleary** [comment]
@HamishBrownPFR - if possible, can you please forward me a 1/2 pager by 16/7 so I can add it to the AI SC papers.

**Comment by sarahcleary** [comment]
@sarchontoulis - as discussed and agreed to in today's RP meeting, could you please forward me a 1/2 pager on NG documentation/training for the AI SC to consider.

**Comment by sarahcleary** [comment]
Notes from July RP meeting - Noted that [Implement new version of SWIM](https://github.com/APSIMInitiative/ApsimX/issues/1254) is being internally funded by AgR and CSIRO.  Outcome should be SWIM into release.  May also include work on [Port the old apsim SoilTemp2 model](https://github.com/APSIMInitiative/ApsimX/issues/4080).  No need to include either as a project for funding from the AI.

Discussion on draft project proposal for [Anaerobic capability for nutrients & ponds](https://github.com/APSIMInitiative/ApsimX/issues/5360) including the scope and structure. Would be ideal if the SWIM model is completed in NG prior to this work being undertaken.  However, Ando's time in constrained to this financial year, so would need to occur concurrently.  Agreed to provide to AI SC for review after amendment.  Retain one face to face workshop but suggest moving others to virtual.   **ACTION**  @Keith-Pembleton to discuss with @DonaldGaydon re: required amendments.

Noted that [New Chickpea Model](https://github.com/APSIMInitiative/ApsimX/issues/158) - work going to be undertaken internally by CSIRO.  No need to include on this list.

Agreed for two more projects to be included on this list - Fixing the Autogeneration NG documentation - @HamishBrownPFR to provide  AND NG documentation and training material - @sarchontoulis to provide

**Comment by sarahcleary** [comment]
As per minutes - https://github.com/APSIMInitiative/ReferencePanel/issues/70  

@HamishBrownPFR discussed potential cofunding for a validation of APSIM datasets
ACTION: @HamishBrownPFR to flesh out a proposal for consideration by RP

@HamishBrownPFR - it possible, could you please circulate prior to the next RP meeting to ensure there is time for consideration/sign off by RP prior to tabling at the next AI SC meeting.

**Comment by sarahcleary** [comment]
@HamishBrownPFR - it possible, could you please circulate prior to the next RP meeting to ensure there is time for consideration/sign off by RP prior to tabling at the next AI SC meeting.

**Comment by peter-devoil** [comment]
The Soybean Module [review](https://github.com/APSIMInitiative/ApsimX/issues/2731#issuecomment-721479267) has mentioned a need for a sprint to address several refactoring, documentation and general apsim improvements that should take place before the module is released. @hut104 indicates this will be some time away.

**Comment by sarahcleary** [comment]
please note outstanding proposals:

@HamishBrownPFR to circulate propose once fleshed out.  Request to send to @sarahcleary to ensure sufficient time for discussion with CSIRO finance with regard to co-funding.
@sarchontoulis to finalise the Root proposal and recirculate to AI RP/SC for final approval - https://github.com/APSIMInitiative/ReferencePanel/issues/71

**Comment by sarahcleary** [comment]
can be reopened when required

**Comment by sarahcleary** [comment]
Noted- possible area for funding - [Improved systems for sensibility tests for all crop models](https://github.com/APSIMInitiative/ApsimX/issues/6517)

**Comment by sno036** [comment]
@sarahcleary - I have some time (and funding, including a subcontract for @hol353 assistance) this year to look into the testing for SWIM3 towards getting it into release. No promises how far it would get this year but this would address [https://github.com/APSIMInitiative/ApsimX/issues/1254]. There is little prospect of being able to test and finish off [https://github.com/APSIMInitiative/ApsimX/issues/4080] without having SWIM3 first. More funding of course would not hurt progress!

**Comment by yashvirchauhan** [comment]
My proposal for AI Funding is attached. Yash Chauha
[Development of alternative models for predicting phenology of chickpeas and lentils.docx](https://github.com/APSIMInitiative/ReferencePanel/files/9430324/Development.of.alternative.models.for.predicting.phenology.of.chickpeas.and.lentils.docx)
n

**Comment by JackieOuzman** [comment]
Thanks
