### ISSUE TITLE
Improved process for model review

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ReferencePanel#63]
The Reference Panel (@APSIMInitiative/reference-panel ) has a set of minimum functional requirements on top of the general requirement for good documentation and a well tested model. (APSIMInitiative/ReferencePanel#61)
These requirements should be communicated to the model reviewers via a simple form.  If the reviewer cannot answer these questions due to technical nature, they can interview the developer to find out how they can determine if requirements are met.  In most cases, the requirements are automatically met through the validation set (e.g. most validation sets include irrigated vs rainfed crops). Almost all models use micromet for all their work.  Many models have some sort of intercropping test as part of the validation set.  It will ordinarily be easy to show that models meet the requirements and so this will not greatly add to the reviewers time but will help them to focus their efforts.
This will save time within the RP in decisions for accepting models after review, and after the response to the review prior to incorporating into the release.

**Comment by sno036** [comment]
Agreed @hut104. The other thing that would assist is a good example of an example simulation showing what is needed by way of testing/demonstrating the usage of the interfaces.

**Comment by sarahcleary** [comment]
@hut104 - with regard to "These requirements should be communicated to the model reviewers via a simple form" -  is this covered by the bottom of this page - https://www.apsim.info/improvements/submission-of-improvements/  "What the reviewer will be looking for" .  With the development guidelines now published - https://apsimnextgeneration.netlify.app/development/ , do you recommend any further changes to either of these?

**Comment by sarahcleary** [comment]
@hut104 - are you happy with my reply.  Can I close this issue?

**Comment by sarahcleary** [comment]
closing issue.  Can be reopened if required.
