### ISSUE TITLE
RP Meeting 6/4

### ISSUE THREAD

**Issue by sarahcleary** [APSIMInitiative/ReferencePanel#84]
The 'placeholder - RP Meeting' will be utilised on 6/4.  Please let me know if it's not showing in your calendar.

Agenda items:
**Eucalyptus model update**
https://github.com/APSIMInitiative/ApsimX/issues/5624#issuecomment-801493766
@sme016 - I have forwarded the meeting invite to you

**Website hosting**
update from @hol353
@hol430 - I have forwarded the meeting invite to you

@APSIMInitiative/reference-panel - please let me know if you have anything else for discussion.

Please note the discussion on the Grape Vine Review - https://github.com/APSIMInitiative/ApsimX/issues/1822  will occur in the May "placeholder" 1 hour slot.

**Comment by sarahcleary** [comment]
@sno036 is on leave.  Please let me know/or comment on this issue, if you are unavailable for this meeting.
I note that @hut104 has another meeting, so we will have the website hosting discussion first.

**Comment by jbrider** [comment]
I'm also on leave, but should be able to dial in .

**Comment by sarahcleary** [comment]
@Keith-Pembleton on leave

**Comment by sarahcleary** [comment]
@APSIMInitiative/reference-panel - please let me know if you are unable to attend Tuesday's meeting.

**Comment by sarahcleary** [comment]
Attendees: @yashvirchauhan; @MarkLieffering; @LouisAK; @peter-devoil; @sarahcleary;  @kchenu; @EnliWang; @jbrider; @HamishBrownPFR; @JulianneLilley; @hol353; @sarchontoulis; @hut104; @hol430; @sme016 

**Website hosting**

@hol353 provided an update on CSIRO IT - they have questioned by CSIRO is hosting all of the AI Infrastructure.  There is an internal move away from hosting non-CSIRO services.  There are two options:
(1) another of the AI members taking over the current role CSIRO provides
(2) move AI Infrastructure to a VM and AI resource required to maintain including security/patches.

Agreed not likely for any other AI member taking over this role

Noted some infrastructure already on VMs. Agree that the plan is to migrate all of the infrastructure to VMs by the end of 2022.  

The AI will need to maintain the domain names, servers, website and related security.

**ACTION:**  @hol353 and @sarahcleary to let CSIRO IT know that the AI will be migrating all AI Infrastructure outside of CSIRO and aim to have this complete by end of 2022.

**Eucalyptus Model**
@sme016 and @hut104 provided an update.
Background - release version was based on AU and BR data sets - tropical and sub-tropical.  Now adding different genotypes - some are different (sub-temperate) species, but dealt with in a similar fashion as new cultivars in crop models.  Want to keep  in one model, as science isn't changing and avoids needing to update more than one model when bugs are found. 
  
Question for the @APSIMInitiative/reference-panel - should these new genotypes go through a full review?  Noted this could occur for other models, one example is the grape model - with different varieties.  

Discussed that statistics change when more data is added.  
**ACTION:** @hut104 and @sme016 to look at the possibility of multiple PO tables for different regions akin to that in the wheat model 

@APSIMInitiative/reference-panel - agreed that no need to review changes for new species if the science is unchanged.  Treat these like new cultivars are treated in crop models

Further discussion on process including the need to check with the addition of new data effects the original .apsimx file.   Agreed that committing one change at a time is preferably - easier to check no inadvertent changes are made.  Good to separate commits of data and changes. Don't merge both at the same time.  

**ACTION:** @hol353 to update Guidelines for Development - https://github.com/APSIMInitiative/ReferencePanel/issues/61 -  to reflect the above conversation.

**Comment by sarahcleary** [comment]
ACTION: @hol353 to update Guidelines for Development - #61 - to reflect the above conversation. 
Complete - refer to https://apsimnextgeneration.netlify.app/development/
